### ISSUE TITLE
Program crashed when remote full baseplate is selected

### ISSUE THREAD

**Issue by ltsai323** [IncandelaLab/SharedUI#15]
Incorrect format recorded in `self.kind_of_part` so the `split()` function report a list index out of range.

# Tested on latest commit be427f21443784af283a4bbee16abd992a14a776
## How to reproduce
Go to search tab and search a Full baseplate from remote. The program crashed immediately.

## Error message from CLI
```
> python3 mainUI.py
Setting up filemanager...
Finished setting up filemanager.  DATADIR is /Users/noises/workspace/SharedUI/filemanager_data
Setting up user manager...
Finished setting up user manager.
Setting up main UI ...
Finished setting up main UI.
Setting up pages' UI...
Finished setting up pages' UI.
Initializing pages...
Finished initializing pages.
Rigging UI...
Finished rigging UI.
page Baseplates not yet setup; doing setup
view_baseplate setup completed
changed to view_baseplate
Set UI page
DB communication is ENABLED
Initializing request box
Initialized request box
Got username ltsai
Got password!
Got username:   ltsai
page Users not yet setup; doing setup
view_users setup completed
ROW: -1
CURRENT USER: None
pre username text:
Setting username text:
changed to view_users
ROW: -1
CURRENT USER: None
pre username text:
Setting username text:
page Search not yet setup; doing setup
search, updateElements
search setup completed
changed to search
changed to view_baseplate
Preparing to upload files for single object: ['/Users/noises/workspace/SharedUI/filemanager_data/baseplates/9-20-2024/baseplate_NTU-test20Sep-full_build_upload.xml', '/Users/noises/workspace/SharedUI/filemanager_data/baseplates/9-20-2024/baseplate_NTU-test20Sep-full_cond_upload.xml']
Starting upload.  Will continue in background.
Scping /Users/noises/workspace/SharedUI/filemanager_data/baseplates/9-20-2024/baseplate_NTU-test20Sep-full_build_upload.xml ...
scp to dbloader successful!
Waiting 15s before uploading the next file...
Scping /Users/noises/workspace/SharedUI/filemanager_data/baseplates/9-20-2024/baseplate_NTU-test20Sep-full_cond_upload.xml ...
scp to dbloader successful!
Finished uploading files.  See GUI status bar for result.
changed to search
changed to view_baseplate

!! Loading baseplate NTU-baseplate-test2-Sep12 from central DB
kind of part: CF/Kapton Baseplate Full
record_insertion_user: Lian-Sheng Tsai (ltsai)
thickness: None, type <class 'NoneType'>
flatness: None
weight: None
grade: None

[Additional Information] self.kind_of_part is ‘CuW/Kapton Baseplate Full’, split() failed to get 4th index.

Traceback (most recent call last):
  File "/Users/noises/workspace/SharedUI/pages/view_baseplate.py", line 104, in wrapped_function
    function(self,*args,**kwargs)
  File "/Users/noises/workspace/SharedUI/pages/view_baseplate.py", line 279, in loadPart
    self.update_info()
  File "/Users/noises/workspace/SharedUI/pages/view_baseplate.py", line 104, in wrapped_function
    function(self,*args,**kwargs)
  File "/Users/noises/workspace/SharedUI/pages/view_baseplate.py", line 172, in update_info
    self.page.cbShape         .setCurrentIndex(INDEX_SHAPE      .get(self.baseplate.geometry          , -1))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noises/workspace/SharedUI/filemanager/parts.py", line 213, in geometry
    return self.kind_of_part.split()[3]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Abort trap: 6
```

## Possible Solution
[Put this line back](https://github.com/IncandelaLab/SharedUI/commit/5358f90b8b57da4c02fe27fd2a95ca477550a4e8#diff-c3c36827fb2cc13e3c95a30652202442444433ef6b5836345f98cbf316f1e83eL213) might skip this issue. Because `self.kind_of_part` does not contains density information.

**Comment by danyi211** [comment]
@ltsai323 Hi Lian-Sheng, I just fixed the issue according to your suggestion, thanks!

**Comment by tvami** [comment]
@ltsai323 is this all good now? Can we close this issue?

**Comment by tvami** [comment]
Please reopen if needed

**Comment by ltsai323** [comment]
Yes everything is good now! Thanks
